-- Books
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-7653-7112-6', 'ADVENTURE', 'The Rising', 'Heather Graham and Jon Land', 'Paperback 2016');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-13-767362-9', 'COMPUTER_FORENSICS', 'Guide To Computer Forensics', 'Bill Nelson, Amelia Phillips, Chris Steuart', '12th Edition');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-19-991811-9', 'CYBERSECURITY', 'Cybersecurity and Cyberwar', 'P.W. Singer and Allan Friedman', '2014');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-1-138-91952-5', 'MANAGEMENT', 'Customer Relationship Management', 'Roger J. Baran and Robert J. Galka', '2nd Edition and paper back');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-1-59749-957-6', 'CYBERSECURITY', 'Violent Python', 'TJ OConnor', 'Publisher Syngress');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('0-02-008095-6', 'EDUCATION', 'The Elements of Business Writing', 'Gary Blake and Robert W. Bly', 'Paperback 1991');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-8048-4241-9', 'EDUCATION', 'Essential Korean', 'Soyeung Koh and Gene Baik', 'Paperback');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-7641-4595-7', 'EDUCATION', 'French Grammar', 'Christopher Kendris and Theodore Kendris', '3rd Edition');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-06-238179-8', 'FICTION', 'Crucible: A Thriller', 'James Rollins', NULL);
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-425-27511-5', 'FICTION', 'Field of Prey', 'John Sandford', 'Paperback 2014');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-7653-8802-5', 'FICTION', 'Vostok: Sequel To The Loch', 'Steve Alten', 'Paperback 2015');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-13-767362-9', 'JAVA', 'CORE JAVA: Volume 1: Fundamentals', 'Cay S. Horstmann', '12th Edition');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('971-08-0428-6', 'RECIPES', 'Philippine Recipes and Other International Recipes', 'Celia Ramos', 'Paperback');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-1-1-62315-651-0', 'RECIPES', 'Seoul Food Korean Cookbook', 'Naomi Imatome-Yun', '12th Edition 2015');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-06-247334-9', 'SCIFI', 'The Andromeda Evolution', 'Michael Crichton', 'Paperback 2019');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-8125-7956-7', 'SCIFI', 'Domain', 'Steve Alten', 'Paperback 2021');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-7653-8798-1', 'SCIFI', 'MEG: Nightstalkers', 'Steve Alten', 'Paperback 2016');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('0-8308-3241-6', 'SPIRITUAL', 'The God Hunt', 'Karen Mains', 'Hardcover 2003');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-310-32536-9', 'SPIRITUAL', 'The Prodigal Son: Discussion Guide', 'Timothy Keller', 'Softbound 2009');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('9780692259986', 'THRILLER', 'Burial Ground', 'Michael McBride', 'Paperback 2011');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-1-250-05106-6', 'THRILLER', 'Paradise Valley', 'C.J. Box', 'Paperback 2018');
INSERT INTO books (isbn, genre, title, book_authors, notes) VALUES('978-0-7653-8465-2', 'THRILLER', 'Strong To The Bone', 'CJ Box', 'Paperback');

-- Readers
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('LUIS_JONES', 'Luis', 'Jones', '755.223.5969', 'lujo725@compress.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('JUAN_LUNA', 'Juan', 'Luna', '503-235-5232', 'jlunax@geemail.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('ELENA_ZARAGOSA', 'Elena', 'Zaragoza', '808-432-1221', 'ez808@hottmail.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('VICENTE_ELIZALDE', 'Vicente', 'Elizalde', '940-521-2309', 'viczal@compress.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('GERALDINE_JAVIER', 'Geraldine', 'Javier', '230-994-4425', 'javine492@geemail.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('OFELIA_ROMEO', 'Ofelia', 'Romeo', '774-229-0592', 'oferom1022@nawawala.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('MARICEL_SMITH', 'Maricel', 'Smith', '404-552-0012', 'marsmi404@hottmail.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('EDWIN_BELMONTE', 'Edwin', 'Belmonte', '678-209-6601', 'edwin_b@village.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('CONCHITA_SALONGA', 'Conchita', 'Salonga', '626-337-3301', 'salonga626@crazywhiz.net');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('CIPRIANO_OCAMPO', 'Cipriano', 'Ocampo', '445-221-7573', 'cocampo445@lapiz.net');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('BRIAN_HERMOSO', 'Brian', 'Hermoso', '266-929-5911', 'hermoso774@whymail.net');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('JOHANNES_LIM', 'Johannes', 'Lim', '339-596-2113', 'gravedang3r@sparklingdrinks.com');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('RODEL_TANDINGAN', 'Rodel', 'Tandingan', '432-777-6666', 'rodel@tunnelinc.net');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('AMON_VELASQUEZ', 'Amon', 'Velasquez', '882-212-0042', 'AmonVel@uniphi.edu');
INSERT INTO readers (reader_id, first_name, last_name, phone, email) VALUES('SNOOKY_SERNA', 'Snooky', 'Serna', '523-876-1960', 'Snoser98765@bienvida.net');